version: '3.5'

services:
  database:
    container_name: database_postgres
    image: postgres:11
    environment:
      POSTGRES_USER: postgres # MODIFY
      POSTGRES_PASSWORD: 123456 # MODIFY
    ports:
      - "5432:5432" # MODIFY
    networks:
      - db-network
    restart: unless-stopped
  
  pgadmin:
    container_name: database_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: gustafsilva.dev@gmail.com # MODIFY
      PGADMIN_DEFAULT_PASSWORD: 123456 # MODIFY
    ports:
      - "80:80"
    networks:
      - db-network
    restart: unless-stopped

networks:
  db-network:
    driver: bridge
